default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: app1_development

test:
  <<: *default
  database: app1_test

production:
  <<: *default
  database: app1_production
  # username: app1
  # password: <%= ENV['APP1_DATABASE_PASSWORD'] %>
